spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://47.97.67.186:3306/mall?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chen

  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
    timeout: 5000ms


#
mybatis-plus:
  #执行sql日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1    # 删除了的值的 delete 为 1
      logic-not-delete-value: 0    # 没有删除的值的 delete 为 0